/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
// build.gradle.kts
allprojects {
    repositories {
        jcenter()
    }
}

// kotlin-demos/settings.gradle.kts
// include("cli-app")
// include 'cli-app'
